service: zxcvbn-on-lambda

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  passwordCalculate:
    handler: handler.endpoint
    events:
      - http:
          path: calculate
          method: post